### PR TITLE
basic changes to get it to run on Android 5.1

### PR DESCRIPTION
**Pull request by AndyScherzinger**
...bumped minSdk to 13 (!), added material light theme, commented out crashlytics

Unfortunately I can't use the app at the moment since I don't have a zulip account nor my own server installation anywhere. But maybe my changed might be of any help to you.

I starts on my phone but I end up on the login screen...

### CODE REVIEW

**Comment by RX14** [comment]
Thanks, I might PR this back to the main repo now.

**Comment by AndyScherzinger** [comment]
Nice! It still needs work design wise since the light theme has a light background and light action bar thus everything is white... which is probably not where one wants to end up

**Comment by RX14** [comment]
Hmmn, I don't have time to do this, but it would be nice to either incorporate @ibit's changes here or the changes here in @ibit's PR.

**Comment by AndyScherzinger** [comment]
Once one of them gets merged into the master of the main repo that shouldn't be a problem. My changes for the Material thing are rather minimal. Problem on my side is that I do not a server side to connect to / login to test drive more than the login screen.

**Comment by RX14** [comment]
The vagrant setup method isn't too difficult to do, you can test using that if you set up your ssh forwarding correctly.

**Comment by RX14** [comment]
Also, @ibit's pr seems to have proguard and the unit tests working, while my fork does not.

**Comment by AndyScherzinger** [comment]
In that case I would suggest go for @ibit's PR and go from there.

As for vagrant, that would mean I would have to set one up which I don't have the time for at the moment :(

**Comment by RX14** [comment]
vagrant is really simple to do, just install vagrant and virtualbox (might already be installed), cd into the git repo, run vagrant up, ssh in, with ssh forwarding, start the server.

**Pull request merged**
